---
- name: app1 to 1 app2 to 3
  hosts: node_88_170
  tasks:
    - name: app1 to 1
      command: sh /root/shell/decrease-app1-to-1.sh

    - name: app2 to 3
      command: sh /root/shell/increase-app2-to-3.sh
